---
title: "Final Project"
author: "Makayla Whitney"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(reticulate)
py_install("cleannlp")
system("pip install cleannlp")
```

```{r code_setup}

#install.packages("cleanNLP")
library(cleanNLP)
library(dplyr)
library(magrittr)
library(ggplot2)
cnlp_init_udpipe()

```

``` {r test}

annotate_test <- cnlp_annotate(input = c(
  "Here is the first text. It is short.",
  "Here's the second. It is short too!",
  "The third text is the shortest."))


d <- annotate_test$token

d %>% 
  count(xpos) %>% 
  filter(xpos != ".") %>% 
  ggplot(aes(n, xpos)) +
  geom_col()


lapply(annotate_test, head)

```

```{r ch1}
annotate_ch1 <- cnlp_annotate(input = c("It was almost December, and Jonas was beginning to be frightened.",
                                        "No. Wrong word, Jonas thought.",
                                        "Frightened meant that deep, sickening feeling of something terrible about to happen.",
                                        "Frightened was the way he had felt a year ago when an unidentified aircraft had overflown the community twice.",
                                        "He had seen it both times.",
                                        "Squinting toward the sky, he had seen the sleek jet, almost a blur at its high speed, go past, and a second later heard the blast of sound that followed.",
                                        "Then one more time, a moment later, from the opposite direction, the same plane.",
                                        "At first, he had been only fascinated.",
                                        "He had never seen aircraft so close, for it was against the rules for Pilots to fly over the community.",
                                        "Occasionally, when supplies were delivered by cargo planes to the landing field across the river, the children rode their bicycles to the riverbank and watched, intrigued, the unloading and then the takeoff directed to the west, always away from the community.",
                                        "But the aircraft a year ago had been different.",
                                        "It was not a squat, fat-bellied cargo plane but a needle-nosed single-pilot jet.",
                                        "Jonas, looking around anxiously, had seen others--adults as well as children--stop what they were doing and wait, confused, for an explanation of the frightening event.",
                                        "Then all of the citizens had been ordered to go into the nearest building and stay there. IMMEDIATELY, the rasping voice through the speakers had said. LEAVE YOUR BICYCLES WHERE THEY ARE.",
                                        "Instantly, obediently, Jonas had dropped his bike on its side on the path behind his family's dwelling.",
                                        "He had run indoors and stayed there, alone.",
                                        "His parents were both at work, and his little sister, Lily, was at the Childcare Center where she spent her after-school hours.",
                                        "Looking through the front window, he had seen no people: none of the busy afternoon crew of Street Cleaners, Landscape Workers, and Food Delivery people who usually populated the community at that time of day.",
                                        "He saw only the abandoned bikes here and there on their sides; an upturned wheel on one was still revolving slowly.",
                                        "He had been frightened then.",
                                        "The sense of his own community silent, waiting, had made his stomach churn. He had trembled.",
                                        "But it had been nothing.",
                                        "Within minutes the speakers had crackled again, and the voice, reassuring now and less urgent, had explained that a Pilot-in-Training had misread his navigational instructions and made a wrong turn.",
                                        "Desperately the Pilot had been trying to make his way back before his error was noticed.",
                                        "NEEDLESS TO SAY, HE WILL BE RELEASED, the voice had said, followed by silence.",
                                        "There was an ironic tone to that final message, as if the Speaker found it amusing; and Jonas had smiled a little, though he knew what a grim statement it had been.",
                                        "For a contributing citizen to be released from the community was a final decision, a terrible punishment, an overwhelming statement of failure.",
                                        "Even the children were scolded if they used the term lightly at play, jeering at a teammate who missed a catch or stumbled in a race.",
                                        "Jonas had done it once, had shouted at his best friend, "That's it, Asher! You're released!" when Asher's clumsy error had lost a match for his team.",
                                        "He had been taken aside for a brief and serious talk by the coach, had hung his head with guilt and embarrassment, and apologized to Asher after the game.",
                                        

Now, thinking about the feeling of fear as he pedaled home along the river path, he remembered that moment of palpable, stomach- sinking terror when the aircraft had streaked above. It was not what he was feeling now with December approaching. He searched for the right word to describe his own feeling.

Jonas was careful about language. Not like his friend, Asher, who talked too fast and mixed things up, scrambling words and phrases until they were barely recognizable and often very funny.

Jonas grinned, remembering the morning that Asher had dashed into the classroom, late as usual, arriving breathlessly in the middle of the chanting of the morning anthem. When the class took their seats at the conclusion of the patriotic hymn, Asher remained standing to make his public apology as was required.

"I apologize for inconveniencing my learning community." Asher ran through the standard apology phrase rapidly, still catching his breath. The Instructor and class waited patiently for his explanation. The students had all been grinning, because they had listened to Asher's explanations so many times before.

"I left home at the correct time but when I was riding along near the hatchery, the crew was separating some salmon. I guess I just got distraught, watching them.

"I apologize to my classmates," Asher concluded. He smoothed his rumpled tunic and sat down.

"We accept your apology, Asher." The class recited the standard response in unison. Many of the students were biting their lips to keep from laughing.

"I accept your apology, Asher," the Instructor said. He was smiling. "And I thank you, because once again you have provided an opportunity for a lesson in language. 'Distraught' is too strong an adjective to describe salmon-viewing." He turned and wrote "distraught" on the instructional board. Beside it he wrote "distracted."

))

lapply(annotate_ch1, head)

```